### PR TITLE
NARPS open pipelines project

### PR DESCRIPTION
**Pull request by cmaumet**

### CODE REVIEW

**Comment by cmaumet** [comment]
@elodiegermani @Remi-Gau @Arshitha @annamenacher and Trang Cao, our abstract on the NARPS open pipelines project at OHBM Brainhack 2022 is available [here](https://github.com/ohbm/hackathon2022proceedings/suites/7527662891/artifacts/310091377) (to view --> unzip and then check `main.pdf`). 

Let us know if you have any feedback or final thoughts!

**Comment by Arshitha** [comment]
Thanks, @cmaumet and @elodiegermani for putting this together! Everything looks great. I wanted to make a very small change to the affiliation section but I couldn't locate the latex file associated with NARPS project on the repo. Currently, it says `2. Intramural Research Program, NIMH, Bethesda, USA;` and if it could be changed to `2. Data Science and Sharing Team (DSST), Intramural Research Program, NIMH, Bethesda, USA;` that'd be great but it's not super-important so if there's a deadline coming up or a word-limit, please ignore this suggestion. Thanks, once again!

**Comment by cmaumet** [comment]
Thanks @Arshitha! I've just updated your affiliation :)

**Review by smoia — APPROVED** [review]
LGTM!

**Comment by cmaumet** [comment]
@elodiegermani @Remi-Gau @Arshitha @annamenacher : the 2022 proceedings are about to be submitted 🎉  As a co-author of our abstract "NARPS open pipelines" can you please all fill in this form:  https://forms.gle/fLnjWLk4dPu1TJjQ7

(as per https://github.com/ohbm/hackathon2022proceedings/issues/15)

Thanks!

**Comment by Remi-Gau** [comment]
Done

**Comment by cmaumet** [comment]
Note: Trang Cao has also confirmed having filled the form in an email exchange 😄

**Comment by Arshitha** [comment]
Done, thanks!

**Comment by annamenacher** [comment]
Done!

**Comment by cmaumet** [comment]
Confirmed for @elodiegermani as well, so all authors have filled the form!

**Comment by smoia** [comment]
@Remi-Gau , your information is missing! Can you fill in the form (again)?

**Comment by Remi-Gau** [comment]
Done... Again. 😘

**Comment by katjaq** [comment]
done for @r03ert0 and me! Thank you :)

**Pull request merged**
